#!/bin/bash

thisdir="$(dirname "$(readlink -f "$0")")"
isx=
case "$(uname -s)" in 'Linux')isx='t';; esac

dprefix='/opt/youtubedl'
ddest="$HOME/mediafiles"
if [ ! "$isx" = 't' ];then
dprefix="$(cygpath -u 'd:/opt/youtubedl')"
ddest="$(cygpath -u 'd:/mediafiles')"
fi
frun="$dprefix/run.sh"

_domain(){
    local domain="$(echo -n "$1"|awk -F/ '{print $3}'|awk -F. '{print $2}')"
    [[ "$domain" =~ ^[a-zA-Z0-9]+$ ]]||unset domain
    printf '%s' "$domain"
}

_run(){
    local url;for url in "$@";do :;done
    case "$url" in http*|https*|HTTP*|HTTPS*);;*)_usage 1;;esac
    local dest="$ddest/dltube$(_domain "$url")"'\%(title)s.%(ext)s'
    if [ ! "$isx" = 't' ];then
    dest="$(cygpath -w "$ddest/dltube$(_domain "$url")")"'\%(title)s.%(ext)s'
    fi
    "$frun" -o "$dest" "$@"
}

_usage(){
	cat<<-EOF
	SYNOPSIS
	    $0 -h
	    $0 --version
	    $0 URL
	EOF
    local rv=0;[ -z "$1" ]||rv="$1"
    exit "$rv"
}
case $1 in
    --version);&
    -h|--help)"$frun" "$@";;
    *)_run "$@";;
esac

#"$PYTHON" "$itemw" --config-location "$configfilew" "$@"
#"$PYTHON" "$itemw" --config-location "$configfilew" -o "$dest" "$@"
#"$frun" --config-location "$configfilew" -o "$dest" "$@"


# configyoutubedl
# -o "D:\mediafiles\dltube\%(title)s.%(ext)s"


#item="$thisdir/youtube-dl"
#[ -f "$item" ]||exit 1
#itemw="$(cygpath -w "$item")"

#PYTHON="$(which python 2>/dev/null)"
#[ -z "$PYTHON" ]&&exit 1

#configfile="$thisdir/configyoutubedl"
#[ -f "$configfile" ]||exit 1
#configfilew="$(cygpath -w "$configfile")"







