#!/bin/bash

#http://ytdl-org.github.io/youtube-dl/download.html
#https://github.com/ytdl-org/youtube-dl
thisdir="$(cd "$(dirname BASH_SOURCE[0])" >/dev/null 2>&1 && pwd)"

url='https://yt-dl.org/downloads/latest/youtube-dl'
dest="$thisdir/youtube-dl"
#destw="$(cygpath -w "$dest")"


curl -L "$url" -o "$dest"


bindir="$HOME/bin"
if [ -d "$bindir" ];then ln -sf "$thisdir/dltube" "$bindir";fi

