#!/bin/bash

#http://ytdl-org.github.io/youtube-dl/download.html
#https://github.com/ytdl-org/youtube-dl
thisdir="$(cd "$(dirname BASH_SOURCE[0])" >/dev/null 2>&1 && pwd)"
url='https://yt-dl.org/downloads/latest/youtube-dl'
dstaging="$thisdir/staging";[ -d "$dstaging" ]||mkdir "$dstaging"

isx=
case "$(uname -s)" in 'Linux')isx='t';; esac

dprefix='/opt/youtubedl'
bindir="$HOME/bin"

if [ ! "$isx" = 't' ];then
dprefix="$(cygpath -u 'd:/opt/youtubedl')"
bindir='d:\bin'
fi

f="$dstaging/${url##*/}"
frun="$dprefix/run.sh"
fpatch="$thisdir/patch.sh"

_download(){
    [ -f "$f" ]||curl -L "$url" -o"$f"
    [ -f "$f" ]||return 1
}
_install(){
    [ -d "$dprefix" ]||mkdir "$dprefix"
    _download \
        && rsync -a --info=progress2 "$f" "$dprefix/" \
        && if [ "$isx" = 't' ];then
            { cat <<-EOF>"$frun"
			#/bin/bash
			dthis="\$(cd "\$(dirname "\$0")" && pwd)"
			_python="\$dthis/env/bin/python"
			"\$_python" "\$dthis/$(basename "$f")" "\$@"
			EOF
            } \
            else
            { cat <<-EOF>"$frun"
			#/bin/bash
			dthis="\$(cd "\$(dirname "\$0")" && pwd)"
			_python="\$dthis/env/Scripts/python"
			"\$_python" "\$(cygpath -w "\$dthis/$(basename "$f")")" "\$@"
			EOF
            } \
            fi \
        && chmod u+x "$frun" \
        && pushd "$dprefix" 2>&1 >/dev/null \
        && virtualenv env \
        && popd >/dev/null \
        && if [ -d "$bindir" ];then ln -sf "$thisdir/dltube" "$bindir";fi

    if [ "$isx" = 't' ];then return 0;fi
    [ ! -f "$fpatch" ]||"$fpatch" --patch

}


_contents(){
    if [ "$isx" = 't' ];then return 1;fi
    [ -f "$f" ]&& 7z l "$(cygpath -w "$f")"
}

_remove(){
    :
    [ -d "$dprefix" ] && (set -x;rm -rf "$dprefix")
    [ -L "$bindir/dltube" ] && (set -x;rm "$bindir/dltube" )
}

_usage(){
	cat<<-EOF
	SYNOPSIS
	    $0 -h
	    $0 --install
	    $0 --remove
	EOF
}
case $1 in
    --install)_install;;
    --remove)_remove;;
    --contents)_contents;;
    *)_usage;;
esac
