#!/bin/bash

#http://ytdl-org.github.io/youtube-dl/download.html
#https://github.com/ytdl-org/youtube-dl
thisdir="$(cd "$(dirname BASH_SOURCE[0])" >/dev/null 2>&1 && pwd)"
droot="$(cd "$thisdir/.."&&pwd)"
url='https://yt-dl.org/downloads/latest/youtube-dl'
dstaging="$droot/staging";[ -d "$dstaging" ]||mkdir "$dstaging"

isx=;case "$(uname -s)" in 'Linux')isx='t';; esac

dprefix='/opt/youtubedl'
bindir="$HOME/bin"
f="$dstaging/${url##*/}"
frun="$dprefix/run.sh"
fpatch="$thisdir/patch.sh"

_download(){
    [ -f "$f" ]||curl -L "$url" -o"$f"
    [ -f "$f" ]||return 1
}
_install(){
    [ -d "$dprefix" ]||(set -x;sudo mkdir "$dprefix")
    _download \
        && sudo rsync -a --info=progress2 "$f" "$dprefix/" \
        && { cat <<-EOF|sudo tee "$frun"
			#/bin/bash
			dthis="\$(cd "\$(dirname "\$0")" && pwd)"
			_python="\$dthis/env/bin/python"
			"\$_python" "\$dthis/$(basename "$f")" "\$@"
			EOF
            } \
        && sudo chmod a+x "$frun" \
        && pushd "$dprefix" 2>&1 >/dev/null \
        && sudo virtualenv env \
        && popd >/dev/null \
        && if [ -d "$bindir" ];then ln -sf "$thisdir/dltube" "$bindir";fi

    [ ! -f "$fpatch" ]||"$fpatch" --patch

}


_contents(){
    #[ -f "$f" ]&& 7z l "$(cygpath -w "$f")"
    [ -f "$f" ]&& 7z l "$f"
    
}

_remove(){
    :
    [ -d "$dprefix" ] && (set -x;sudo rm -rf "$dprefix")
    [ -L "$bindir/dltube" ] && (set -x;rm "$bindir/dltube" )
}

_usage(){
	cat<<-EOF
	SYNOPSIS
	    $0 -h
	    $0 --install
	    $0 --remove
	EOF
}
case $1 in
    --install)_install;;
    --remove)_remove;;
    --contents)_contents;;
    *)_usage;;
esac
